### PR TITLE
refactored printing of progress for increased readability

### PR DESCRIPTION
**Pull request by jspaaks**
## Description

refactored printing of progress for increased readability

Refs: continuation of PR #100 

* * *

## Before you get started

- [ ] I read and I followed [contributing guidelines](https://github.com/tortellini-tools/action/blob/main/CONTRIBUTING.md)
- [ ] [☝ Create an issue](https://github.com/NLeSC/licenseguard/issues/new/choose) to discuss what you are going to do

## Checklist

This section should be filled in by the creator of this pull request to make sure the pull request is ready to review.

- [x] This pull request has a descriptive title
- [x] Code is written according to the code quality guidelines
- [x] Documentation if applicable is available
- [x] Tests run successfully
- [x] All checks below this pull request were successful

## Instructions to review the pull request

1. github actions should be green
2. &nbsp;

    ```
    cd $(mktemp -d --tmpdir tortellini.XXXXXX)
    node ${where your repo clone is}/dist/index.js # should work
    ```

### CODE REVIEW

**Review by eriktks — APPROVED** [review]
1. checked refactored `dist/index.js` and `scr/check.ts`. They looked fine
2. checked Github actions, should be green: OK
3. blindly ran `dist/index.js` locally: finished without any problem

**Comment by jspaaks** [comment]
Hey Erik thanks for the review. I'm a bit puzzled by the `dist/action` thing. I think something isnt up to date in your setup perhaps.

Below, I gave more robust instructions on how to make sure I didnt break anything in the PR. Could you give them a try? Thanks!

```
cd $(mktemp -d --tmpdir tortellini.XXXXXX)
git clone https://github.com/tortellini-tools/action .
git checkout refactor-progress-string
npm install
npm run build
npm run package
node dist/index.js
```

**Review by eriktks — APPROVED** [review]
Clarified!

**Comment by jspaaks** [comment]
ignoring github actions here, they are being addressed in PR #109

**Pull request merged**
